### PR TITLE
814 message bug

### LINKED ISSUE #814: Reset code message bug
Ive found a small bug when sending many reset codes. I think only one of these messages should appear at a time, both appearing is condescending and confusing to the user.

Only show success or error, have them overwrite each other.

bug-reset-message

### PR DESCRIPTION
**Pull request by ConorTighe1995**
Both an error and success message can no longer be displayed as a response when attempting to reset the password. Now its only one or the other.

closes #814

### CODE REVIEW

**Comment by ConorTighe1995** [comment]
I think there is a way to do this without the render function so I changed this to WIP for now.

**Comment by ConorTighe1995** [comment]
> I think there is a way to do this without the render function so I changed this to WIP for now.

I refactored it, actually required very little changes in the end just some linting changes and a state change.

File: src/components/authentication/ResetPassword.jsx [hunk 1]
```diff
@@ -34,36 +34,10 @@ class ResetPassword extends React.Component {
       isError: true,
       errorMessage: message,
       pending: false,
+      isSuccess: false,
```
Comment (ConorTighe1995) [inline src/components/authentication/ResetPassword.jsx:37]: Where the magic happens.
