### PR TITLE
fixes url parsing of process from url; will not open an unfound proce…

### LINKED ISSUE #204: error when loading processes
see screenshot!

image

I believe this happens when some processes no longer exist on the backend or are somehow otherwise 'un-fetchable'

I know this is a problem @vdiezel has encountered before, so how can we put our heads together and find a good solution to make it so this bad state is either not gotten into, or a way that when it does happen we reasonably handle it for the user

### LINKED ISSUE #206: Get filter working for devices
Currently, the filter does not work

Please get it working to filter by name (MVP)
If more filters are needed later, we will add them as they are required.

image

### PR DESCRIPTION
**Pull request by DanielSeehausen**
…ss and break

this actually closes #204  - name of branch is wrong.

### CODE REVIEW

File: src/components/device/Device.jsx [hunk 1]
```diff
@@ -57,9 +58,18 @@ class Device extends React.Component {
     <DeviceSetup activeDevice={getActiveDevice(this.props.devices, this.props.match.params.deviceId)}/>
   )
 
-  renderProcessScreen = () => (
-    <ProcessScreen activeDevice={getActiveDevice(this.props.devices, this.props.match.params.deviceId)}/>
-  )
+  renderProcessScreen = () => {
+    const activeProcess = getActiveProcess(this.props.processes, this.props.match.params.processId)
+    const activeDevice = getActiveDevice(this.props.devices, this.props.match.params.deviceId)
+
```
Comment (DanielSeehausen) [inline src/components/device/Device.jsx]: this is not ideal - and I created a ticket to implement a better solution #211

File: src/components/devices/Devices.jsx [hunk 2]
```diff
@@ -4,21 +4,22 @@ import { connect } from "react-redux"
 import { withRouter } from "react-router-dom"
 import DeviceList from './DeviceList'
 import { resetActiveDevice } from "../../redux/actions/actions"
-import { callCreateDevice, callGetDevices, callGetProcesses } from "../../redux/thunks/thunks"
+import { callStopProcess, callCreateDevice, callGetDevices, callGetProcesses } from "../../redux/thunks/thunks"
```
Comment (DanielSeehausen) [inline src/components/devices/Devices.jsx]: this is being used to fix an ongoing error in a block of code not present in this PR :/
I will take out soon

File: src/components/main/Main.jsx [hunk 3]
```diff
@@ -108,6 +108,7 @@ class Main extends React.Component {
             <Route exact path='/about' component={About}/>
             <Route exact path='/profile' component={Profile}/>
             <Route exact path='/notifications' component={Notifications}/>
+            <Route path='/device/:deviceId/process/:processId' component={Device}/>
```
Comment (DanielSeehausen) [inline src/components/main/Main.jsx]: this sneaky devil was matching on line 112 below, and then never actually populating the matched :processId param, making it inaccessible
