### PR TITLE
524 add loader to alerts and fix margin

### LINKED ISSUE #524: Add loader to alerts and fix margin

### PR DESCRIPTION
**Pull request by O-Susanoo**
closes #524

### CODE REVIEW

File: src/components/alerts/Alerts.jsx [hunk 1]
```diff
@@ -35,11 +38,21 @@ const Alerts = ({ user, devices, dispatchGetDevices, dispatchDeleteUserAlert, de
...
+    }
+
+    if (!devicesInitialized) {
+      loadDevices()
     }
-    loadMissingData()
+
+    if (devicesInitialized) {
+      displayAlerts()
+    }
```
Comment (DanielSeehausen) [inline src/components/alerts/Alerts.jsx]: 👁 
some unneeded verbosity snuck in here!

File: src/components/alerts/Alerts.jsx [hunk 2]
```diff
@@ -18,12 +18,15 @@ const mapDispatchToProps = dispatch => ({
 })
 
 const Alerts = ({ user, devices, dispatchGetDevices, dispatchDeleteUserAlert, devicesInitialized }) => {
-  const [populatedAlerts, setAlerts] = React.useState([])
+  const [state, setState] = React.useState({ loading: false, populatedAlerts: [] })
+  const { loading, populatedAlerts } = state
```
Comment (DanielSeehausen) [inline src/components/alerts/Alerts.jsx]: consider pushing this way down to above where things start rendering, in the interest of declaring variables as close to their use as possible!
